import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Listen for push notifications from the server
self.addEventListener('push', event => {
  let data = {};
  try {
    data = event.data ? event.data.json() : {};
  } catch (e) {
    console.error('Push event data is not JSON:', event.data?.text());
    data = { title: '🐷 Farm Alert', body: event.data ? event.data.text() : '' };
  }
  
  const title = data.title || '🐷 Farm Alert';
  const options = {
    body: data.body || 'Something needs your attention on the farm!',
    icon: '/favicon.svg', // Use favicon.svg or standard icons
    badge: '/favicon.svg',
    data: {
      url: data.url || '/'
    },
    vibrate: [200, 100, 200],
    actions: [
      { action: 'open', title: 'Open App' }
    ]
  };

  event.waitUntil(
    self.registration.showNotification(title, options)
  );
});

// Handle clicking on the notification
self.addEventListener('notificationclick', event => {
  event.notification.close();
  
  const targetUrl = event.notification.data?.url || '/';
  
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(windowClients => {
      // Check if we already have a window open at that URL
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        if (client.url.includes(targetUrl) && 'focus' in client) {
          return client.focus();
        }
      }
      // If not, open a new window
      if (clients.openWindow) {
        return clients.openWindow(targetUrl);
      }
    })
  );
});
